### ISSUE TITLE
Required Packages & Directory

### ISSUE THREAD

**Issue by SMCJB** [kjhealy/uk-elections#1]
Hi, 
I'm very new to R and to Github. 
I installed the packages I was missing and ran the code only to find that I was still missing 'gdata' (called on line 154) and 'mapproj' so you may want to add these to the library calls at the top.
Also the code seemed to fail for me as it was trying to write to the 'figures' subdirectory but that directory didn't exist. Adding the directory manually fixed this.
Still working through some other issues.

**Comment by SMCJB** [comment]
Sorry the library(gdata) call is at line 148 (not 154) and again at line 267

**Comment by SMCJB** [comment]
Regards to gdata you can't just move the library call to the top with the other library statements because it is detached later on and hence has to be recalled.

**Comment by kjhealy** [comment]
Thanks. The code now checks for a `figures` subdirectory and creates it if it's not there. 

I just use the `gdata` library quickly to recode some factors. Because it masks some other functions we load and unload it as needed.
