### ISSUE TITLE
Two more issues

### ISSUE THREAD

**Issue by SMCJB** [kjhealy/uk-elections#2]
1) Code can not find 'constituency_names.df'. 
I believe this is because the code checks to see whether "data/constituency_names.csv" exists but if it does (already exist) it doesn't actually load it.
2) Code can not find function credit() called on lines 303 and 356

Other than that code runs perfectly for me. I do get an error that I don't have a perl interpreter installed but since we never load an xls file I dont think that matters unless of course that is related to the credit() function call.

**Comment by micahstubbs** [comment]
I experience error 1) as well

![5-11-2015 7 40 14 am](https://cloud.githubusercontent.com/assets/2119400/7564922/fa61de68-f7b0-11e4-9de5-b3af651533c2.png)

**Comment by SMCJB** [comment]
You should probably add it as an `else` but I just added something like

```
if(file.exists("data/constituency_names.csv")){constituency_names.df <- 
    read.csv(file="data/constituency_names.csv")}
```

**Comment by kjhealy** [comment]
Fixed; thanks
