### ISSUE TITLE
could not find function "read_html"

### ISSUE THREAD

**Issue by micahstubbs** [kjhealy/uk-elections#3]
@kjhealy many thanks for sharing the dataset and the script.  When I attempt to run the first two sections in RStudio I encounter this error:

`Error in eval(expr, envir, enclos) : could not find function "read_html"`

![5-11-2015 7 43 13 am](https://cloud.githubusercontent.com/assets/2119400/7564959/65157062-f7b1-11e4-8459-83c44ea5d576.png)

**Comment by kjhealy** [comment]
read_html is in the `rvest` library, which needs to be installed.

**Comment by micahstubbs** [comment]
thanks @kjhealy ! I'll sort out my dependencies.  really appreciate the answer.

**Comment by kjhealy** [comment]
To be a bit clearer—I think you'll need the development version of rvest, installed from github. https://github.com/hadley/rvest

**Comment by akshaynagpal** [comment]
Dev version not installing @kjhealy 

```
> install_github("hadley/rvest")
Downloading github repo hadley/rvest@master
Installing rvest
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/advance/AppData/Local/Temp/RtmpO6mdNM/devtools203c6e031676/hadley-rvest-    9461bc4"  \
  --library="C:/Users/advance/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'rvest' ...
** R    
** demo
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (rvest)
Reloading installed rvest
unloadNamespace("rvest") not successful. Forcing unload.
```
